# fly.toml app configuration file
app = "nome-do-seu-app"  # substitua pelo nome do app que você criou no fly.io
primary_region = "gru"  # ou outra região próxima de você (gru = São Paulo)

[build]
  # Se você já tem um Dockerfile na raiz, não precisa definir nada aqui
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false   # impede que a instância "durma"
  auto_start_machines = true   # garante restart automático
  min_machines_running = 1     # mantém pelo menos 1 rodando sempre
  processes = ["app"]

[[services]]
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"
    restart_limit = 0